package io.github.homepy.whale.calcite.cs.po.pbc;

/** 人行报告住房公积金信息表(CSP_PBC_HOUSEFUND) */
public class CspPbcHouseFund {

	/** 报告编号 */
	public String reportid;
	/** 个人帐号 */
	public String account;
	/** 单位名称 */
	public String comp_nm;
	/** 开户日期 */
	public String acc_open_date;
	/** 初缴年月 */
	public String pay_date_s;
	/** 缴至年月 */
	public String pay_date_e;
	/** 最近一次交缴日期 */
	public String recent_pay_date;
	/** 单位缴存比例 */
	public String pay_deposit_com;
	/** 个人缴存比例 */
	public String pay_deposit_per;
	/** 月缴存额 */
	public String month_pay_deposit;
	/** 信息获取时间 */
	public String info_date;
	/** 24月缴费情况 */
	public String retst24;
	/** 23月缴费情况 */
	public String retst23;
	/** 22月缴费情况 */
	public String retst22;
	/** 21月缴费情况 */
	public String retst21;
	/** 20月缴费情况 */
	public String retst20;
	/** 19月缴费情况 */
	public String retst19;
	/** 18月缴费情况 */
	public String retst18;
	/** 17月缴费情况 */
	public String retst17;
	/** 16月缴费情况 */
	public String retst16;
	/** 15月缴费情况 */
	public String retst15;
	/** 14月缴费情况 */
	public String retst14;
	/** 13月缴费情况 */
	public String retst13;
	/** 12月缴费情况 */
	public String retst12;
	/** 11月缴费情况 */
	public String retst11;
	/** 10月缴费情况 */
	public String retst10;
	/** 9月缴费情况 */
	public String retst9;
	/** 8月缴费情况 */
	public String retst8;
	/** 7月缴费情况 */
	public String retst7;
	/** 6月缴费情况 */
	public String retst6;
	/** 5月缴费情况 */
	public String retst5;
	/** 4月缴费情况 */
	public String retst4;
	/** 3月缴费情况 */
	public String retst3;
	/** 2月缴费情况 */
	public String retst2;
	/** 1月缴费情况 */
	public String retst1;
	/** 参缴地 */
	public String area;
}
