package io.github.homepy.whale.calcite.cs.po.pbc;

/** 人行报告贷款明细表(CSP_PBC_LOANLIST) */
public class CspPbcLoanList {

	/** 报告编号 */
	public String reportid;
	/** 贷款种类 */
	public String loan_type;
	/** 担保方式 */
	public String vouch_type;
	/** 币种 */
	public String currency_type;
	/** 帐户状态 */
	public String account_state;
	/** 还款频率 */
	public String ret_frequency;
	/** 还款月数 */
	public String ret_month;
	/** YYYY.MM.DD */
	public String loandate_s;
	/** YYYY.MM.DD */
	public String loandate_e;
	/** 贷款合同金额 */
	public String loan_amount;
	/** 贷款余额 */
	public String loan_balance;
	/** YYYY.MM.DD */
	public String info_date;
	/** 剩余还款月数 */
	public String rest_month;
	/** YYYY.MM.DD */
	public String recent_ret_date;
	/** 本月应还款金额 */
	public String cur_month_need;
	/** 本月实际还款金额 */
	public String cur_month_return;
	/** 当前逾期期数 */
	public String overdue_count;
	/** 当前逾期总额 */
	public String overdue_sum;
	/** 累计逾期次数 */
	public String total_overdue;
	/** 最高逾期期数 */
	public String top_overdue;
	/** 逾期31-60天未归还贷款本金 */
	public String overdue1;
	/** 逾期61-90天未归还贷款本金 */
	public String overdue2;
	/** 逾期91-180天未归还贷款本金 */
	public String overdue3;
	/** 逾期180天以上未归还贷款本金 */
	public String overdue4;
	/** 24月的缴费情况 */
	public String retst24;
	/** 23月的缴费情况 */
	public String retst23;
	/** 22月的缴费情况 */
	public String retst22;
	/** 21月的缴费情况 */
	public String retst21;
	/** 20月的缴费情况 */
	public String retst20;
	/** 19月的缴费情况 */
	public String retst19;
	/** 18月的缴费情况 */
	public String retst18;
	/** 17月的缴费情况 */
	public String retst17;
	/** 16月的缴费情况 */
	public String retst16;
	/** 15月的缴费情况 */
	public String retst15;
	/** 14月的缴费情况 */
	public String retst14;
	/** 13月的缴费情况 */
	public String retst13;
	/** 12月的缴费情况 */
	public String retst12;
	/** 11月的缴费情况 */
	public String retst11;
	/** 10月的缴费情况 */
	public String retst10;
	/** 9月的缴费情况 */
	public String retst9;
	/** 8月的缴费情况 */
	public String retst8;
	/** 7月的缴费情况 */
	public String retst7;
	/** 6月的缴费情况 */
	public String retst6;
	/** 5月的缴费情况 */
	public String retst5;
	/** 4月的缴费情况 */
	public String retst4;
	/** 3月的缴费情况 */
	public String retst3;
	/** 2月的缴费情况 */
	public String retst2;
	/** 1月的缴费情况 */
	public String retst1;
	/** 结算年月 */
	public String balance_date;
	/** 贷款机构名称 */
	public String loan_orgname;
	/** 还款状态记录-编号 */
	public String ret_code;
	/** 业务号 */
	public String tran_code;
	/** 贷款机构类型 */
	public String loan_orgtype;
	/** 账户类型 */
	public String account_type;
}
